### ISSUE TITLE
Ability to query overall course/grading category (i.e. exams or projects) grade

### ISSUE THREAD

**Issue by rpkenney** [nfoster1492/ClassMateBot-1#10]

**Comment by nfoster1492** [comment]
We ended up doing two separate methods to solve this issue. One that works for the entire course grade and another that allows the input of a category to get an overall category grade. In order to get the overall course grade, we used a weighted value for each category in the categories table of the database. We decided to then query through each category's assignments and grades and add them up based on the overall weights.
