### ISSUE TITLE
Ability to determine what you need on a given assignment to keep a certain grade in the class / grading category

### ISSUE THREAD

**Issue by rpkenney** [nfoster1492/ClassMateBot-1#11]

**Comment by nfoster1492** [comment]
We discussed whether or not to include this command and ultimately decided it was beneficial for students because we always needed to do this for our own courses. We again created two methods, one for the entire course and one for individual categories based on input from the user. We used an algorithm to determine what grade would be needed on the next assignment, given its category and points value, to keep a specified grade in the overall class or a category.
