### ISSUE TITLE
Command to export calendar to pdf and print out

### ISSUE THREAD

**Issue by rpkenney** [nfoster1492/ClassMateBot-1#4]
- options for how you want it viewed (i.e. provide a date range and it will give you a breakdown by day/week/month etc)

**Comment by brwali** [comment]
I can make a command to export the calendar as a pdf, but I believe that should be the end of the functionality for this command so not print it out.

**Comment by brwali** [comment]
A discussion was held on our discord server and this change is acceptable. In addition, I had also questioned if this was command was necessary since we had a command to export to ical and we decided it still was. This command was also verified by also another dev but tests still need to be written.
